package sk.upjs.ics.todo.gui;

import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableRowSorter;
import sk.upjs.ics.todo.dao.Factory;
import sk.upjs.ics.todo.dao.PrihlasovaciARegistrovaciServis;
import sk.upjs.ics.todo.entity.Uloha;
import sk.upjs.ics.todo.dao.UlohaDao;
import sk.upjs.ics.todo.modely.UlohaTableModel;

public class MainForm extends javax.swing.JFrame {

    private static final UlohaDao ulohaDao = Factory.INSTANCE.ulohaDao();

    private static final UlohaTableModel ulohaTableModel = new UlohaTableModel();

    private static final TableRowSorter ulohyRowSorter = new TableRowSorter(ulohaTableModel);

    private static final PrihlasovaciARegistrovaciServis prihlasovaciARegistrovaciServis
            = PrihlasovaciARegistrovaciServis.INSTANCE;

    public MainForm() {
        initComponents();

        GuiFactory.INSTANCE.centruj(this);
        tblUloha.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                tblUlohaSelectionValueChanged(e);
            }
        });
        tblUloha.setModel(ulohaTableModel);
        tblUloha.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUloha.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUlohaMouseClicked(evt);
            }
        });

        lblPouzivatel.setText(prihlasovaciARegistrovaciServis.getPouzivatel().getMeno());
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        aktualizujZoznamUloh();
    }

    //ak je nejaká úloha vybratá, umožní stlačenie tlačidiel "vymaž" a "uprav"
    private void tblUlohaSelectionValueChanged(ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {
            if (!tblUloha.getSelectionModel().isSelectionEmpty()) {
                btnVymaz.setEnabled(true);
                btnUprav.setEnabled(true);
            } else {
                btnVymaz.setEnabled(false);
                btnUprav.setEnabled(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblZnacka = new javax.swing.JLabel();
        btnPridaj = new javax.swing.JButton();
        btnUprav = new javax.swing.JButton();
        btnVymaz = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUloha = new javax.swing.JTable();
        btnDnesne = new javax.swing.JButton();
        btnTentoTyzden = new javax.swing.JButton();
        btnTentoMesiac = new javax.swing.JButton();
        btnVsetky = new javax.swing.JButton();
        btnKategorie = new javax.swing.JButton();
        btnFilters = new javax.swing.JButton();
        lblPouzivatel = new javax.swing.JLabel();
        btnOdhlas = new javax.swing.JButton();
        btnGrafy = new javax.swing.JButton();
        btnNotifikacie = new javax.swing.JButton();
        lblPozadie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TODO list aka DORI");
        setMinimumSize(new java.awt.Dimension(502, 285));
        setResizable(false);
        getContentPane().setLayout(null);

        lblZnacka.setBackground(new java.awt.Color(204, 153, 255));
        lblZnacka.setFont(new java.awt.Font("Gungsuh", 0, 36)); // NOI18N
        lblZnacka.setText("dori");
        getContentPane().add(lblZnacka);
        lblZnacka.setBounds(380, 160, 70, 43);

        btnPridaj.setBackground(new java.awt.Color(204, 204, 204));
        btnPridaj.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnPridaj.setText("pridaj...");
        btnPridaj.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPridaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridajActionPerformed(evt);
            }
        });
        getContentPane().add(btnPridaj);
        btnPridaj.setBounds(307, 11, 66, 26);

        btnUprav.setBackground(new java.awt.Color(204, 204, 204));
        btnUprav.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnUprav.setText("uprav...");
        btnUprav.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUprav.setEnabled(false);
        btnUprav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpravActionPerformed(evt);
            }
        });
        getContentPane().add(btnUprav);
        btnUprav.setBounds(307, 48, 66, 25);

        btnVymaz.setBackground(new java.awt.Color(204, 204, 204));
        btnVymaz.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnVymaz.setText("vymaž");
        btnVymaz.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVymaz.setEnabled(false);
        btnVymaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVymazActionPerformed(evt);
            }
        });
        getContentPane().add(btnVymaz);
        btnVymaz.setBounds(307, 84, 66, 25);

        tblUloha.setBackground(new java.awt.Color(204, 204, 204));
        tblUloha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblUloha.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        tblUloha.setModel(ulohaTableModel);
        tblUloha.setGridColor(new java.awt.Color(204, 204, 204));
        tblUloha.setRowSorter(ulohyRowSorter);
        tblUloha.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblUloha);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 10, 266, 200);

        btnDnesne.setBackground(new java.awt.Color(204, 204, 204));
        btnDnesne.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        btnDnesne.setText("Dnešné");
        btnDnesne.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDnesne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDnesneActionPerformed(evt);
            }
        });
        getContentPane().add(btnDnesne);
        btnDnesne.setBounds(20, 220, 50, 23);

        btnTentoTyzden.setBackground(new java.awt.Color(204, 204, 204));
        btnTentoTyzden.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnTentoTyzden.setText("Tento týždeň");
        btnTentoTyzden.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTentoTyzden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentoTyzdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnTentoTyzden);
        btnTentoTyzden.setBounds(70, 220, 90, 23);

        btnTentoMesiac.setBackground(new java.awt.Color(204, 204, 204));
        btnTentoMesiac.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnTentoMesiac.setText("Tento mesiac");
        btnTentoMesiac.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTentoMesiac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentoMesiacActionPerformed(evt);
            }
        });
        getContentPane().add(btnTentoMesiac);
        btnTentoMesiac.setBounds(160, 220, 100, 23);

        btnVsetky.setBackground(new java.awt.Color(204, 204, 204));
        btnVsetky.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnVsetky.setText("Všetky");
        btnVsetky.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVsetky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVsetkyActionPerformed(evt);
            }
        });
        getContentPane().add(btnVsetky);
        btnVsetky.setBounds(260, 220, 50, 23);

        btnKategorie.setBackground(new java.awt.Color(204, 204, 204));
        btnKategorie.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnKategorie.setText("Kategórie...");
        btnKategorie.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnKategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategorieActionPerformed(evt);
            }
        });
        getContentPane().add(btnKategorie);
        btnKategorie.setBounds(415, 10, 80, 30);

        btnFilters.setBackground(new java.awt.Color(204, 204, 204));
        btnFilters.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnFilters.setText("Filtre...");
        btnFilters.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltersActionPerformed(evt);
            }
        });
        getContentPane().add(btnFilters);
        btnFilters.setBounds(415, 45, 80, 30);

        lblPouzivatel.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblPouzivatel.setText("Neprihlásený");
        getContentPane().add(lblPouzivatel);
        lblPouzivatel.setBounds(420, 230, 90, 14);

        btnOdhlas.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnOdhlas.setText("Odhlás");
        btnOdhlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdhlasActionPerformed(evt);
            }
        });
        getContentPane().add(btnOdhlas);
        btnOdhlas.setBounds(420, 210, 70, 20);

        btnGrafy.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnGrafy.setText("Grafy...");
        btnGrafy.setMaximumSize(new java.awt.Dimension(75, 17));
        btnGrafy.setMinimumSize(new java.awt.Dimension(75, 17));
        btnGrafy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafyActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrafy);
        btnGrafy.setBounds(415, 80, 80, 30);

        btnNotifikacie.setFont(new java.awt.Font("Gungsuh", 0, 8)); // NOI18N
        btnNotifikacie.setText("Notifikácie");
        btnNotifikacie.setMaximumSize(new java.awt.Dimension(75, 17));
        btnNotifikacie.setMinimumSize(new java.awt.Dimension(75, 17));
        btnNotifikacie.setPreferredSize(new java.awt.Dimension(75, 17));
        btnNotifikacie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotifikacieActionPerformed(evt);
            }
        });
        getContentPane().add(btnNotifikacie);
        btnNotifikacie.setBounds(415, 115, 80, 23);

        lblPozadie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainform.jpg"))); // NOI18N
        getContentPane().add(lblPozadie);
        lblPozadie.setBounds(0, 0, 500, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //otvorí addForm na vytvorenie úlohy + refresh
    private void btnPridajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridajActionPerformed
        AddEditUlohyForm addForm = new AddEditUlohyForm(this);
        addForm.setVisible(true);

        aktualizujZoznamUloh();
    }//GEN-LAST:event_btnPridajActionPerformed

    //otvorí addForm na editáciu úlohy + refresh
    private void btnUpravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpravActionPerformed
        int vybranyRiadok = tblUloha.getSelectedRow();
        int vybranyIndexVModeli = tblUloha.convertRowIndexToModel(vybranyRiadok);

        Uloha vybranaUloha = ulohaTableModel.dajPodlaCislaRiadku(vybranyIndexVModeli);

        AddEditUlohyForm editForm = new AddEditUlohyForm(vybranaUloha, this);
        editForm.setVisible(true);

        aktualizujZoznamUloh();
    }//GEN-LAST:event_btnUpravActionPerformed

    //vymaže vybranú úlohu pomocou dialógového okna
    private void btnVymazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVymazActionPerformed
        int vybranyRiadok = tblUloha.getSelectedRow();
        int vybratyIndexVModeli = tblUloha.convertRowIndexToModel(vybranyRiadok);

        Uloha vybrataUloha
                = ulohaTableModel.dajPodlaCislaRiadku(vybratyIndexVModeli);

        if (vybrataUloha == null) {
            return;
        }

        int tlacidlo = JOptionPane.showConfirmDialog(this,
                "Naozaj odstrániť?",
                "Odstránenie úlohy",
                JOptionPane.YES_NO_OPTION
        );
        if (tlacidlo == JOptionPane.YES_OPTION) {
            ulohaDao.vymazUlohu(vybrataUloha);
            aktualizujZoznamUloh();
        }
    }//GEN-LAST:event_btnVymazActionPerformed

    //zobrazí dnešné úlohy
    private void btnDnesneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDnesneActionPerformed
        ulohaTableModel.filtruj(ulohaDao.dajDnesne());
    }//GEN-LAST:event_btnDnesneActionPerformed

    //zobrazí všetky úlohy
    private void btnVsetkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVsetkyActionPerformed
        aktualizujZoznamUloh();
    }//GEN-LAST:event_btnVsetkyActionPerformed

    //zobrazí úlohy na tento mesiac
    private void btnTentoMesiacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentoMesiacActionPerformed
        ulohaTableModel.filtruj(ulohaDao.dajMesacne());
    }//GEN-LAST:event_btnTentoMesiacActionPerformed

    //zobrazí úlohy na tento týždeň
    private void btnTentoTyzdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentoTyzdenActionPerformed
        ulohaTableModel.filtruj(ulohaDao.dajTyzdnove());
    }//GEN-LAST:event_btnTentoTyzdenActionPerformed

    //otvorí menežéra kategórií (v novom okne)
    private void btnKategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategorieActionPerformed
        KategorieForm kategorie = new KategorieForm(this, true);
        kategorie.setVisible(true);
    }//GEN-LAST:event_btnKategorieActionPerformed

    //otvorí sekciu "filtrovanie" (v novom okne)
    private void btnFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltersActionPerformed
        FiltrovaniaForm filter = new FiltrovaniaForm(this, true);
        filter.setVisible(true);
    }//GEN-LAST:event_btnFiltersActionPerformed

    private void btnOdhlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdhlasActionPerformed
        prihlasovaciARegistrovaciServis.odhlas();
        // ak sa pouzivatel odhlasi, tak sa spusti prihlasovacie okno...
        PrihlasovanieForm.main(null);
        // ...a aktualne sa zavrie
        dispose();
    }//GEN-LAST:event_btnOdhlasActionPerformed

    // otvori okno s vyberom obdobia pre graf
    private void btnGrafyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafyActionPerformed
        VyberObdobiaPreGrafForm vyberObdobiaPreGrafForm = new VyberObdobiaPreGrafForm(this, true);
        vyberObdobiaPreGrafForm.setVisible(true);
    }//GEN-LAST:event_btnGrafyActionPerformed

    // otvori okno s nastavenim notifikacii
    private void btnNotifikacieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotifikacieActionPerformed
        NotifikacieForm notifikacieForm = new NotifikacieForm(this, true);
        notifikacieForm.setVisible(true);
    }//GEN-LAST:event_btnNotifikacieActionPerformed

    // zabezpečí, že po dvojkliku myšou sa zobrazí detail úlohy, na ktorú sa kliklo
    private void tblUlohaMouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            int vybranyRiadok = tblUloha.getSelectedRow();
            int vybratyIndexVModeli = tblUloha.convertRowIndexToModel(vybranyRiadok);

            Uloha vybrataUloha
                    = ulohaTableModel.dajPodlaCislaRiadku(vybratyIndexVModeli);

            if (vybrataUloha == null) {
                return;
            }
            DetailUlohaForm detail = new DetailUlohaForm(vybrataUloha, this);
            detail.setVisible(true);
            // ked ma niekto zobrazene nepr. mesacne, tak sa mu ten vyber 
            // resetuje, preto tu aktualizaciu vypneme
            // aktualizujZoznamUloh();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDnesne;
    private javax.swing.JButton btnFilters;
    private javax.swing.JButton btnGrafy;
    private javax.swing.JButton btnKategorie;
    private javax.swing.JButton btnNotifikacie;
    private javax.swing.JButton btnOdhlas;
    private javax.swing.JButton btnPridaj;
    private javax.swing.JButton btnTentoMesiac;
    private javax.swing.JButton btnTentoTyzden;
    private javax.swing.JButton btnUprav;
    private javax.swing.JButton btnVsetky;
    private javax.swing.JButton btnVymaz;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPouzivatel;
    private javax.swing.JLabel lblPozadie;
    private javax.swing.JLabel lblZnacka;
    private javax.swing.JTable tblUloha;
    // End of variables declaration//GEN-END:variables

    //refresh
    private void aktualizujZoznamUloh() {
        ulohaTableModel.obnov();
    }
}
