package sk.upjs.ics.todo.gui;

import java.awt.Frame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import sk.upjs.ics.todo.dao.Factory;
import sk.upjs.ics.todo.dao.PouzivatelDao;
import sk.upjs.ics.todo.dao.PrihlasovaciARegistrovaciServis;

public class NotifikacieForm extends javax.swing.JDialog {

    // budeme potrebovat upravit udaje o pouzivatelovi
    private static final PouzivatelDao pouzivatelDao = Factory.INSTANCE.pouzivatelDao();

    private static final VerifikatorVstupov verifikator = GuiFactory.INSTANCE.getVerifikatorVstupov();

    public NotifikacieForm(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        GuiFactory.INSTANCE.centruj(this);
        getContentPane().setBackground(GuiFactory.INSTANCE.getFarbaPozadia());

        chkChceNotifikacie.setSelected(PrihlasovaciARegistrovaciServis.INSTANCE.getPouzivatel().isChceNotifikacie());
        Integer dobaNotifikacie = PrihlasovaciARegistrovaciServis.INSTANCE.getPouzivatel().getDobaNotifikacie();
        if (dobaNotifikacie == null) {
            txtDobaNotifikacie.setText("");
        } else {
            txtDobaNotifikacie.setText(Integer.toString(dobaNotifikacie));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnUlozit = new javax.swing.JButton();
        btnZavriet = new javax.swing.JButton();
        lblCasNotifikacie = new javax.swing.JLabel();
        chkChceNotifikacie = new javax.swing.JCheckBox();
        txtDobaNotifikacie = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); // NOI18N

        btnUlozit.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnUlozit.setText("Uložiť");
        btnUlozit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozitActionPerformed(evt);
            }
        });

        btnZavriet.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnZavriet.setText("Storno");
        btnZavriet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZavrietActionPerformed(evt);
            }
        });

        lblCasNotifikacie.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblCasNotifikacie.setText("hod. pred časom splnenia úlohy");

        chkChceNotifikacie.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        chkChceNotifikacie.setText("Chcem dostávať na mail notifikácie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDobaNotifikacie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCasNotifikacie))
                    .addComponent(chkChceNotifikacie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnZavriet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUlozit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addComponent(chkChceNotifikacie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDobaNotifikacie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCasNotifikacie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUlozit)
                    .addComponent(btnZavriet))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZavrietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZavrietActionPerformed
        dispose();
    }//GEN-LAST:event_btnZavrietActionPerformed

    /**
     * Ulozi nove nastavenia notifikacii pre prihlaseneho pouzivatela
     *
     * @param evt
     */
    private void btnUlozitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozitActionPerformed
        PrihlasovaciARegistrovaciServis.INSTANCE.getPouzivatel().setChceNotifikacie(chkChceNotifikacie.isSelected());

        String dobaNotifikacie = txtDobaNotifikacie.getText();
        // overenie pre pripad, ze uzivatel nezadal do doby notifikacie nic
        if (dobaNotifikacie.isEmpty()) {
            PrihlasovaciARegistrovaciServis.INSTANCE.getPouzivatel().setDobaNotifikacie(null);
        } // ak zadal cislo v zlom formate
        else if (!verifikator.jeCeleKladneCislo(txtDobaNotifikacie)) {
            JOptionPane.showMessageDialog(this,
                    "Zadajte dobu notifikácie v správnom formáte!\n"
                    + "Maximálne hodnotu " + Integer.MAX_VALUE + "!",
                    verifikator.getNadpis(), ERROR_MESSAGE);
            return;
        } else {
            PrihlasovaciARegistrovaciServis.INSTANCE.getPouzivatel().setDobaNotifikacie(Integer.valueOf(dobaNotifikacie));
        }

        pouzivatelDao.upravNotifikacie(PrihlasovaciARegistrovaciServis.INSTANCE.getPouzivatel());
        dispose();
    }//GEN-LAST:event_btnUlozitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotifikacieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotifikacieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotifikacieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotifikacieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NotifikacieForm dialog = new NotifikacieForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUlozit;
    private javax.swing.JButton btnZavriet;
    private javax.swing.JCheckBox chkChceNotifikacie;
    private javax.swing.JLabel lblCasNotifikacie;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JTextField txtDobaNotifikacie;
    // End of variables declaration//GEN-END:variables
}
