package sk.ics.upjs.todo.gui;

import java.awt.Frame;
import java.util.List;
import javax.swing.ComboBoxModel;
import sk.ics.upjs.todo.dao.Factory;
import sk.ics.upjs.todo.dao.FilterDao;
import sk.ics.upjs.todo.dao.KategoriaDao;
import sk.ics.upjs.todo.home.Filter;
import sk.ics.upjs.todo.home.Kategoria;

public class AddEditFiltreForm extends javax.swing.JDialog {

    private static final FilterDao filterDao = Factory.INSTANCE.filterDao();
    private static final KategoriaDao kategoriaDao = Factory.INSTANCE.kategoriaDao();
    private Filter filter;
    private static final ComboBoxModel comboBoxModel = Factory.INSTANCE.getKategoryCmbModel();
    private boolean add = false;

    public AddEditFiltreForm(Frame parent) {
        this(new Filter(), parent);
        this.add = true;
    }

    public AddEditFiltreForm(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AddEditFiltreForm(Filter vybranyFilter, Frame parent) {
        this(parent, true);
        this.setTitle("menežovanie filtrov");
        this.filter = vybranyFilter;
        if (filter.getKategoria() != null) {
            cmbKategoria.setSelectedItem(filter.getKategoria().getNazov());
        }
        cmbPriorita.setSelectedItem(filter.getPriorita());

        if (filter.isStav() == false) {
            cmbStav.setSelectedItem("Nesplnená");
        } else {
            cmbStav.setSelectedItem("Splnená");
        }
        txtNazov.setText(filter.getNazov());
        if (filter.getDatumOd() != null) {
            String datumOd = filter.getDatumOd();
            cmbDenOd.setSelectedItem(datumOd.substring(8, 10));
            cmbMesOd.setSelectedItem(datumOd.substring(5, 7));
            cmbRokOd.setSelectedItem(datumOd.substring(0, 4));
        }
        if (filter.getDatumDo() != null) {
            String datumDo = filter.getDatumDo();
            cmbDenDo.setSelectedItem(datumDo.substring(8, 10));
            cmbMesDo.setSelectedItem(datumDo.substring(5, 7));
            cmbRokDo.setSelectedItem(datumDo.substring(0, 4));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblZnacka = new javax.swing.JLabel();
        lblKategoria = new javax.swing.JLabel();
        lblPriorita = new javax.swing.JLabel();
        lblStav = new javax.swing.JLabel();
        lblDatumOd = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNazov = new javax.swing.JTextField();
        lblDatumDo = new javax.swing.JLabel();
        cmbKategoria = new javax.swing.JComboBox();
        cmbStav = new javax.swing.JComboBox();
        cmbDenOd = new javax.swing.JComboBox();
        cmbMesOd = new javax.swing.JComboBox();
        cmbRokOd = new javax.swing.JComboBox();
        cmbDenDo = new javax.swing.JComboBox();
        cmbMesDo = new javax.swing.JComboBox();
        cmbRokDo = new javax.swing.JComboBox();
        cmbPriorita = new javax.swing.JComboBox();
        lblPozadie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(490, 230));
        getContentPane().setLayout(null);

        lblZnacka.setBackground(new java.awt.Color(204, 153, 255));
        lblZnacka.setFont(new java.awt.Font("Gungsuh", 0, 36)); // NOI18N
        lblZnacka.setText("dori");
        getContentPane().add(lblZnacka);
        lblZnacka.setBounds(380, 130, 85, 42);

        lblKategoria.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblKategoria.setText("kategória");
        getContentPane().add(lblKategoria);
        lblKategoria.setBounds(10, 49, 59, 14);

        lblPriorita.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblPriorita.setText("priorita");
        getContentPane().add(lblPriorita);
        lblPriorita.setBounds(20, 84, 49, 14);

        lblStav.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblStav.setText("stav");
        getContentPane().add(lblStav);
        lblStav.setBounds(41, 124, 28, 14);

        lblDatumOd.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblDatumOd.setText("dátum od");
        getContentPane().add(lblDatumOd);
        lblDatumOd.setBounds(240, 14, 52, 14);

        btnOK.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK);
        btnOK.setBounds(398, 80, 47, 23);

        jLabel1.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("názov");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 17, 59, 14);

        txtNazov.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        txtNazov.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        getContentPane().add(txtNazov);
        txtNazov.setBounds(87, 11, 120, 30);

        lblDatumDo.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblDatumDo.setText("dátum do");
        getContentPane().add(lblDatumDo);
        lblDatumDo.setBounds(240, 45, 52, 14);

        cmbKategoria.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbKategoria.setModel(comboBoxModel);
        getContentPane().add(cmbKategoria);
        cmbKategoria.setBounds(87, 47, 120, 20);

        cmbStav.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbStav.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Splnená", "Nesplnená" }));
        getContentPane().add(cmbStav);
        cmbStav.setBounds(87, 121, 120, 20);

        cmbDenOd.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbDenOd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmbDenOd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDenOdActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDenOd);
        cmbDenOd.setBounds(302, 11, 50, 20);

        cmbMesOd.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbMesOd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(cmbMesOd);
        cmbMesOd.setBounds(357, 11, 50, 20);

        cmbRokOd.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbRokOd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(cmbRokOd);
        cmbRokOd.setBounds(412, 11, 57, 20);

        cmbDenDo.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbDenDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmbDenDo);
        cmbDenDo.setBounds(302, 42, 50, 20);

        cmbMesDo.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbMesDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(cmbMesDo);
        cmbMesDo.setBounds(357, 41, 50, 20);

        cmbRokDo.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbRokDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(cmbRokDo);
        cmbRokDo.setBounds(412, 41, 57, 20);

        cmbPriorita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Nízka", "Stredná", "Vysoká" }));
        getContentPane().add(cmbPriorita);
        cmbPriorita.setBounds(87, 83, 120, 20);

        lblPozadie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addeditfiltreform.jpg"))); // NOI18N
        getContentPane().add(lblPozadie);
        lblPozadie.setBounds(0, 0, 500, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed

        StringBuilder datumOd = new StringBuilder();
        if (!cmbRokOd.getSelectedItem().toString().equals(" ")) {
            datumOd.append(cmbRokOd.getSelectedItem().toString());
        } else {
            datumOd.append("2014");
        }
        if (!cmbMesOd.getSelectedItem().toString().equals(" ")) {
            datumOd.append(cmbMesOd.getSelectedItem().toString());
        } else {
            datumOd.append("01");
        }
        if (!cmbDenOd.getSelectedItem().toString().equals(" ")) {
            datumOd.append(cmbDenOd.getSelectedItem().toString());
        } else {
            datumOd.append("01");
        }

        StringBuilder datumDo = new StringBuilder();

        if (!cmbRokDo.getSelectedItem().toString().equals(" ")) {
            datumDo.append(cmbRokDo.getSelectedItem().toString());
        } else {
            datumDo.append("2022");
        }
        if (!cmbMesDo.getSelectedItem().toString().equals(" ")) {
            datumDo.append(cmbMesDo.getSelectedItem().toString());
        } else {
            datumDo.append("12");
        }
        if (!cmbDenDo.getSelectedItem().toString().equals(" ")) {
            datumDo.append(cmbDenDo.getSelectedItem().toString());
        } else {
            datumDo.append("31");
        }
        List<Kategoria> vsetkyKategorie = kategoriaDao.dajVsetky();
        String nazovKat = cmbKategoria.getSelectedItem().toString();
        Kategoria pridavanaKategoria = null;
        for (Kategoria kategoria : vsetkyKategorie) {
            if (kategoria.getNazov().equals(nazovKat)) {
                pridavanaKategoria = kategoria;
            }
        }

        filter.setNazov(txtNazov.getText().trim());
        filter.setDatumOd(datumOd.toString());
        filter.setDatumDo(datumDo.toString());
        filter.setKategoria(pridavanaKategoria);
        if (cmbPriorita.getSelectedItem() != null) {
            filter.setPriorita(cmbPriorita.getSelectedItem().toString());
        } else {
            filter.setPriorita(" ");
        }
        if (cmbStav.getSelectedItem().toString().equals("Splnená")) {
            filter.setStav(true);
        } else {
            filter.setStav(false);
        }
        if (add) {
            filterDao.pridajFilter(filter);
        } else {
            filterDao.upravFilter(filter);
        }
        dispose();

    }//GEN-LAST:event_btnOKActionPerformed

    private void cmbDenOdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDenOdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDenOdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditFiltreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditFiltreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditFiltreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditFiltreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEditFiltreForm dialog = new AddEditFiltreForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cmbDenDo;
    private javax.swing.JComboBox cmbDenOd;
    private javax.swing.JComboBox cmbKategoria;
    private javax.swing.JComboBox cmbMesDo;
    private javax.swing.JComboBox cmbMesOd;
    private javax.swing.JComboBox cmbPriorita;
    private javax.swing.JComboBox cmbRokDo;
    private javax.swing.JComboBox cmbRokOd;
    private javax.swing.JComboBox cmbStav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDatumDo;
    private javax.swing.JLabel lblDatumOd;
    private javax.swing.JLabel lblKategoria;
    private javax.swing.JLabel lblPozadie;
    private javax.swing.JLabel lblPriorita;
    private javax.swing.JLabel lblStav;
    private javax.swing.JLabel lblZnacka;
    private javax.swing.JTextField txtNazov;
    // End of variables declaration//GEN-END:variables

}
