package sk.ics.upjs.todo.gui;

import java.awt.Frame;
import java.util.List;
import javax.swing.*;
import sk.ics.upjs.todo.dao.Factory;
import sk.ics.upjs.todo.home.Kategoria;
import sk.ics.upjs.todo.dao.KategoriaDao;
import sk.ics.upjs.todo.home.Uloha;
import sk.ics.upjs.todo.dao.UlohaDao;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

public class AddEditUlohyForm extends javax.swing.JDialog {

    private static final UlohaDao ulohaDao = Factory.INSTANCE.ulohaDao();
    private static final KategoriaDao kategoriaDao = Factory.INSTANCE.kategoriaDao();
    private static final ComboBoxModel modelKategorii = Factory.INSTANCE.getKategoryCmbModel();
    private Uloha uloha;

    private boolean add = false;
    
    //konštruktory na pridávanie úlohy
    public AddEditUlohyForm(Frame parent) {
        this(new Uloha(), parent);
        this.add = true;
    }

    public AddEditUlohyForm(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    //konštruktor na editáciu úlohy, všetky parametre úlohy vyplní do príslušných okienok
    public AddEditUlohyForm(Uloha uloha, Frame parent) {
        this(parent, true);
        this.setTitle("Pridanie/editácia úlohy");
        this.uloha = uloha;
        txtPopis.setText(uloha.getPopis());
        txtNazov.setText(uloha.getNazov());
        if (uloha.getKategoria() != null) {
            cmbKategoria.setSelectedItem(uloha.getKategoria().getNazov());
        }
        cmbPriorita.setSelectedItem(uloha.getPriorita());

        if (uloha.getDatum() != null) {
            String datum = uloha.getDatum();
            cmbDen.setSelectedItem(datum.substring(8, 10));

            cmbMesiac.setSelectedItem(datum.substring(5, 7));

            cmbRok.setSelectedItem(datum.substring(0, 4));
        }

        if (uloha.getCas() != null) {
            String cas = uloha.getCas();
            txtMinuty.setText(cas.substring(3, 5));

            txtHodiny.setText(cas.substring(0, 2));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblZnacka = new javax.swing.JLabel();
        lblZnacka1 = new javax.swing.JLabel();
        lblUloha = new javax.swing.JLabel();
        lblPopis = new javax.swing.JLabel();
        lblPriorita = new javax.swing.JLabel();
        lblKategoria = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        txtNazov = new javax.swing.JTextField();
        txtPopis = new javax.swing.JTextField();
        cmbPriorita = new javax.swing.JComboBox();
        cmbKategoria = new javax.swing.JComboBox();
        cmbDen = new javax.swing.JComboBox();
        cmbMesiac = new javax.swing.JComboBox();
        cmbRok = new javax.swing.JComboBox();
        lblCas = new javax.swing.JLabel();
        txtHodiny = new javax.swing.JTextField();
        txtMinuty = new javax.swing.JTextField();
        lblDvojbodka = new javax.swing.JLabel();
        lblPozadie = new javax.swing.JLabel();

        lblZnacka.setBackground(new java.awt.Color(204, 153, 255));
        lblZnacka.setFont(new java.awt.Font("Gungsuh", 0, 36)); // NOI18N
        lblZnacka.setText("dori");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(462, 268));
        setResizable(false);
        getContentPane().setLayout(null);

        lblZnacka1.setBackground(new java.awt.Color(204, 153, 255));
        lblZnacka1.setFont(new java.awt.Font("Gungsuh", 0, 36)); // NOI18N
        lblZnacka1.setText("dori");
        getContentPane().add(lblZnacka1);
        lblZnacka1.setBounds(340, 200, 99, 42);

        lblUloha.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        lblUloha.setText("úloha");
        getContentPane().add(lblUloha);
        lblUloha.setBounds(90, 11, 35, 15);

        lblPopis.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        lblPopis.setText("detail");
        getContentPane().add(lblPopis);
        lblPopis.setBounds(22, 42, 35, 15);

        lblPriorita.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        lblPriorita.setText("priorita");
        getContentPane().add(lblPriorita);
        lblPriorita.setBounds(62, 183, 46, 15);

        lblKategoria.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        lblKategoria.setText("kategória");
        getContentPane().add(lblKategoria);
        lblKategoria.setBounds(62, 207, 56, 15);

        lblDatum.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        lblDatum.setText("dátum");
        getContentPane().add(lblDatum);
        lblDatum.setBounds(239, 63, 33, 15);

        btnOk.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        btnOk.setText("OK");
        btnOk.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk);
        btnOk.setBounds(362, 95, 40, 24);

        txtNazov.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        txtNazov.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        txtNazov.setBorder(null);
        getContentPane().add(txtNazov);
        txtNazov.setBounds(140, 10, 185, 15);

        txtPopis.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        txtPopis.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        txtPopis.setBorder(null);
        getContentPane().add(txtPopis);
        txtPopis.setBounds(22, 63, 199, 100);

        cmbPriorita.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        cmbPriorita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Nízka", "Stredná", "Vysoká" }));
        getContentPane().add(cmbPriorita);
        cmbPriorita.setBounds(131, 177, 90, 21);

        cmbKategoria.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        cmbKategoria.setModel(modelKategorii);
        getContentPane().add(cmbKategoria);
        cmbKategoria.setBounds(131, 204, 90, 21);

        cmbDen.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        cmbDen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmbDen);
        cmbDen.setBounds(278, 63, 50, 21);

        cmbMesiac.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        cmbMesiac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(cmbMesiac);
        cmbMesiac.setBounds(332, 63, 50, 21);

        cmbRok.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        cmbRok.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(cmbRok);
        cmbRok.setBounds(385, 63, 70, 21);

        lblCas.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        lblCas.setText("čas");
        getContentPane().add(lblCas);
        lblCas.setBounds(239, 104, 22, 15);

        txtHodiny.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        txtHodiny.setText("00");
        txtHodiny.setBorder(null);
        getContentPane().add(txtHodiny);
        txtHodiny.setBounds(265, 104, 26, 15);

        txtMinuty.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        txtMinuty.setText("00");
        txtMinuty.setBorder(null);
        getContentPane().add(txtMinuty);
        txtMinuty.setBounds(303, 104, 26, 15);

        lblDvojbodka.setFont(new java.awt.Font("Gungsuh", 0, 12)); // NOI18N
        lblDvojbodka.setText(":");
        getContentPane().add(lblDvojbodka);
        lblDvojbodka.setBounds(295, 104, 4, 15);

        lblPozadie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addeditulohyform.jpg"))); // NOI18N
        getContentPane().add(lblPozadie);
        lblPozadie.setBounds(0, -10, 460, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ak sú všetky parametre úlohy zadané, úloha sa uloží alebo zedituje
    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (overNeprazdnostKomponentov()) {
            StringBuilder datum = new StringBuilder();
            datum.append(cmbRok.getSelectedItem().toString())
                    .append(cmbMesiac.getSelectedItem().toString())
                    .append(cmbDen.getSelectedItem().toString());
            uloha.setDatum(datum.toString());
            List<Kategoria> vsetkyKategorie = kategoriaDao.dajVsetky();
            String nazovKat = cmbKategoria.getSelectedItem().toString();
            Kategoria pridavanaKategoria = null;
            for (Kategoria kategoria : vsetkyKategorie) {
                if (kategoria.getNazov().equals(nazovKat)) {
                    pridavanaKategoria = kategoria;
                }
            }
            uloha.setKategoria(pridavanaKategoria);
            uloha.setPopis(txtPopis.getText());
            uloha.setNazov(txtNazov.getText());
            uloha.setStav(false);
            uloha.setPriorita(cmbPriorita.getSelectedItem().toString());
            StringBuilder cas = new StringBuilder();
            cas.append(txtHodiny.getText()).append(txtMinuty.getText()).append("00");
            uloha.setCas(cas.toString());

            if (add) {
                ulohaDao.pridajUlohu(uloha);
            } else {
                ulohaDao.upravUlohu(uloha);
            }
            dispose();
        }
    }//GEN-LAST:event_btnOkActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditUlohyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditUlohyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditUlohyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditUlohyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEditUlohyForm dialog = new AddEditUlohyForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cmbDen;
    private javax.swing.JComboBox cmbKategoria;
    private javax.swing.JComboBox cmbMesiac;
    private javax.swing.JComboBox cmbPriorita;
    private javax.swing.JComboBox cmbRok;
    private javax.swing.JLabel lblCas;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDvojbodka;
    private javax.swing.JLabel lblKategoria;
    private javax.swing.JLabel lblPopis;
    private javax.swing.JLabel lblPozadie;
    private javax.swing.JLabel lblPriorita;
    private javax.swing.JLabel lblUloha;
    private javax.swing.JLabel lblZnacka;
    private javax.swing.JLabel lblZnacka1;
    private javax.swing.JTextField txtHodiny;
    private javax.swing.JTextField txtMinuty;
    private javax.swing.JTextField txtNazov;
    private javax.swing.JTextField txtPopis;
    // End of variables declaration//GEN-END:variables

    
    //metóda zistí, či sú vo všetkých okienkach zadané údaje
    private boolean overNeprazdnostKomponentov() {
        String sprava = new String();
        Boolean podmienka = true;

        if (txtNazov.getText().isEmpty()) {
            sprava = "Vyplň názov.";
            podmienka = false;
        }
        if (txtPopis.getText().isEmpty()) {
            sprava = "Vyplň popis.";
            podmienka = false;
        }
        if (cmbKategoria.getSelectedItem().toString().equals(" ")) {
            sprava = "Vyber kategóriu";
            podmienka = false;
        }
        if (cmbPriorita.getSelectedItem().toString().equals(" ")) {
            sprava = "Vyber prioritu";
            podmienka = false;
        }
        if (cmbDen.getSelectedItem().toString().equals(" ")) {
            sprava = "Vyber deň";
            podmienka = false;
        }
        if (cmbMesiac.getSelectedItem().toString().equals(" ")) {
            sprava = "Vyber mesiac";
            podmienka = false;
        }
        if (cmbRok.getSelectedItem().toString().equals(" ")) {
            sprava = "Vyber rok";
            podmienka = false;
        }
        if (txtMinuty.getText().isEmpty()) {
            sprava = "Zadaj minuty";
            podmienka = false;
        }
        if (txtHodiny.getText().isEmpty()) {
            sprava = "Zadaj hodiny";
            podmienka = false;
        }
        if (!txtMinuty.getText().matches("[0-9\\.]+")
                || txtMinuty.getText().length() > 2) {
            sprava = "Nesprávny formát minút.";
            podmienka = false;
        }
        if (!txtHodiny.getText().matches("[0-9\\.]+")
                || txtHodiny.getText().length() > 2) {
            sprava = "Nesprávny formát hodín.";
            podmienka = false;
        }

        if (!podmienka) {
            JOptionPane.showMessageDialog(this, sprava, "Chyba", ERROR_MESSAGE);
        }

        return podmienka;
    }

}
