package sk.ics.upjs.todo.gui;

import java.awt.Frame;
import sk.ics.upjs.todo.home.Uloha;

public class DetailUlohaForm extends javax.swing.JDialog {
    
    private Uloha uloha;

    /**
     * Creates new form DetailForm
     */
    public DetailUlohaForm() {
        initComponents();
    }
    
    public DetailUlohaForm(Frame parent) {
        this(parent, true);
        this.setTitle("Detail úlohy");
    }
    
    public DetailUlohaForm(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    //konštruktor, vytvorí detailné okno s údajmi o vybrane úlohe
    public DetailUlohaForm(Uloha uloha, Frame parent) {
        this(parent, true);
        this.uloha = uloha;
        lblPopis.setText(uloha.getPopis());
        lblNazov.setText(uloha.getNazov());
        lblPriorita.setText(uloha.getPriorita());
        
        String datum = uloha.getDatum().trim();
        StringBuilder zobrazDatum = new StringBuilder();
        zobrazDatum.append(datum.substring(8, 10)).append(".").append(datum.substring(5, 7))
                .append(".").append(datum.substring(0, 4));
        lblDatum.setText(zobrazDatum.toString());
        
        String cas = uloha.getCas();
        StringBuilder zobrazCas = new StringBuilder();
        zobrazCas.append(cas.substring(0, 2)).append(":").append(cas.substring(3, 5));
        lblCas.setText(zobrazCas.toString());
        lblKategoria.setText(uloha.getKategoria().getNazov());
        if (uloha.getStav()) {
            lblStav.setText("Splnená");
        } else {
            lblStav.setText("Nesplnená");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNazov = new javax.swing.JLabel();
        lblZnacka1 = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblCas = new javax.swing.JLabel();
        lblPriorita = new javax.swing.JLabel();
        lblPopis = new javax.swing.JLabel();
        lblDatumUkazovatel = new javax.swing.JLabel();
        lblPrioritaUkazovatel = new javax.swing.JLabel();
        lblStavUkazovatel = new javax.swing.JLabel();
        lblKategoria = new javax.swing.JLabel();
        lblKategoriaUkazovatel = new javax.swing.JLabel();
        lblStav = new javax.swing.JLabel();
        lblPozadie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(445, 285));
        getContentPane().setLayout(null);

        lblNazov.setFont(new java.awt.Font("Gungsuh", 1, 12)); // NOI18N
        lblNazov.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        lblNazov.setOpaque(true);
        getContentPane().add(lblNazov);
        lblNazov.setBounds(10, 10, 220, 22);

        lblZnacka1.setBackground(new java.awt.Color(204, 153, 255));
        lblZnacka1.setFont(new java.awt.Font("Gungsuh", 0, 36)); // NOI18N
        lblZnacka1.setText("dori");
        getContentPane().add(lblZnacka1);
        lblZnacka1.setBounds(340, 200, 99, 42);

        lblDatum.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblDatum.setOpaque(true);
        getContentPane().add(lblDatum);
        lblDatum.setBounds(40, 200, 99, 22);

        lblCas.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblCas.setOpaque(true);
        getContentPane().add(lblCas);
        lblCas.setBounds(150, 200, 80, 23);

        lblPriorita.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblPriorita.setOpaque(true);
        getContentPane().add(lblPriorita);
        lblPriorita.setBounds(280, 30, 120, 22);

        lblPopis.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblPopis.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        lblPopis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPopis.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblPopis.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblPopis.setMaximumSize(new java.awt.Dimension(430, 240));
        lblPopis.setOpaque(true);
        lblPopis.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblPopis);
        lblPopis.setBounds(10, 40, 220, 140);

        lblDatumUkazovatel.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblDatumUkazovatel.setText("do:");
        getContentPane().add(lblDatumUkazovatel);
        lblDatumUkazovatel.setBounds(10, 200, 17, 22);

        lblPrioritaUkazovatel.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblPrioritaUkazovatel.setText("priorita:");
        getContentPane().add(lblPrioritaUkazovatel);
        lblPrioritaUkazovatel.setBounds(280, 10, 99, 19);

        lblStavUkazovatel.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblStavUkazovatel.setText("stav:");
        getContentPane().add(lblStavUkazovatel);
        lblStavUkazovatel.setBounds(280, 130, 90, 20);

        lblKategoria.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblKategoria.setOpaque(true);
        getContentPane().add(lblKategoria);
        lblKategoria.setBounds(280, 90, 120, 20);

        lblKategoriaUkazovatel.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblKategoriaUkazovatel.setText("kategória:");
        getContentPane().add(lblKategoriaUkazovatel);
        lblKategoriaUkazovatel.setBounds(280, 70, 90, 14);

        lblStav.setOpaque(true);
        getContentPane().add(lblStav);
        lblStav.setBounds(280, 150, 120, 20);

        lblPozadie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/detailform.jpg"))); // NOI18N
        lblPozadie.setMaximumSize(new java.awt.Dimension(430, 250));
        lblPozadie.setMinimumSize(new java.awt.Dimension(430, 250));
        lblPozadie.setPreferredSize(new java.awt.Dimension(430, 250));
        getContentPane().add(lblPozadie);
        lblPozadie.setBounds(0, 0, 430, 250);
        lblPozadie.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailUlohaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailUlohaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailUlohaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailUlohaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailUlohaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCas;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDatumUkazovatel;
    private javax.swing.JLabel lblKategoria;
    private javax.swing.JLabel lblKategoriaUkazovatel;
    private javax.swing.JLabel lblNazov;
    private javax.swing.JLabel lblPopis;
    private javax.swing.JLabel lblPozadie;
    private javax.swing.JLabel lblPriorita;
    private javax.swing.JLabel lblPrioritaUkazovatel;
    private javax.swing.JLabel lblStav;
    private javax.swing.JLabel lblStavUkazovatel;
    private javax.swing.JLabel lblZnacka1;
    // End of variables declaration//GEN-END:variables
}
