package sk.ics.upjs.todo.gui;

import java.awt.Frame;
import java.awt.event.MouseEvent;
import java.util.*;
import javax.swing.ComboBoxModel;
import sk.ics.upjs.todo.home.FilterTableModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sk.ics.upjs.todo.dao.Factory;
import sk.ics.upjs.todo.dao.FilterDao;
import sk.ics.upjs.todo.dao.UlohaDao;
import sk.ics.upjs.todo.home.Filter;
import sk.ics.upjs.todo.home.Uloha;
import sk.ics.upjs.todo.home.UlohaTableModel;

public class FiltrovaniaForm extends javax.swing.JDialog {

    private static final UlohaTableModel ulohaTableModel = new UlohaTableModel();
    private static final FilterDao filterDao = Factory.INSTANCE.filterDao();
    private static final UlohaDao ulohaDao = Factory.INSTANCE.ulohaDao();
    private static final FilterTableModel filterTableModel = new FilterTableModel();
    private static final ComboBoxModel comboBoxModel = Factory.INSTANCE.getKategoryCmbModel();

    public FiltrovaniaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("filtre");
        tblFiltre.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                tblFiltreSelectionValueChanged(e);
            }
        });
        tblUloha.setModel(ulohaTableModel);
        tblUloha.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUlohaMouseClicked(evt);
            }
        });
        tblFiltre.setModel(filterTableModel);
        tblFiltre.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFiltreMouseClicked(evt);
            }
        });
        // setDefaultCloseOperation(EXIT_ON_CLOSE);
        aktualizujZoznamUloh();
        aktualizujZoznamFiltrov();
    }

    private void tblFiltreSelectionValueChanged(ListSelectionEvent e) {
        if (!e.getValueIsAdjusting()) {
            if (!tblFiltre.getSelectionModel().isSelectionEmpty()) {
                btnVymaz.setEnabled(true);
                btnUprav.setEnabled(true);
            } else {
                btnVymaz.setEnabled(false);
                btnUprav.setEnabled(false);
            }
        }
    }

    private void tblFiltreMouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            int vybranyRiadok = tblFiltre.getSelectedRow();
            int vybranyIndexVModeli = tblFiltre.convertRowIndexToModel(vybranyRiadok);

            Filter vybranyFilter = filterTableModel.dajPodlaCislaRiadku(vybranyIndexVModeli);

            if (vybranyFilter == null) {
                return;
            }

            cmbKategoria.setSelectedItem(vybranyFilter.getKategoria().getNazov());
            cmbPriorita.setSelectedItem(vybranyFilter.getPriorita());
            if (vybranyFilter.isStav() == false) {
                cmbStav.setSelectedItem("Nesplnená");
            } else {
                cmbStav.setSelectedItem("Splnená");
            }
            if (vybranyFilter.getDatumOd() != null) {
                String datumOd = vybranyFilter.getDatumOd();
                cmbDenOd.setSelectedItem(datumOd.substring(8, 10));
                cmbMesOd.setSelectedItem(datumOd.substring(5, 7));
                cmbRokOd.setSelectedItem(datumOd.substring(0, 4));
            }
            if (vybranyFilter.getDatumDo() != null) {
                String datumDo = vybranyFilter.getDatumDo();
                cmbDenDo.setSelectedItem(datumDo.substring(8, 10));
                cmbMesDo.setSelectedItem(datumDo.substring(5, 7));
                cmbRokDo.setSelectedItem(datumDo.substring(0, 4));
            }
        }
    }

    private void tblUlohaMouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            int vybranyRiadok = tblUloha.getSelectedRow();
            int vybratyIndexVModeli = tblUloha.convertRowIndexToModel(vybranyRiadok);

            Uloha vybrataUloha
                    = ulohaTableModel.dajPodlaCislaRiadku(vybratyIndexVModeli);

            if (vybrataUloha == null) {
                return;
            }
            DetailUlohaForm detail = new DetailUlohaForm(vybrataUloha, (Frame) getOwner());
            detail.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblZnacka = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUloha = new javax.swing.JTable();
        lblKategoria = new javax.swing.JLabel();
        lblPriorita = new javax.swing.JLabel();
        lblStav = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblUvod = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFiltre = new javax.swing.JTable();
        btnPridaj = new javax.swing.JButton();
        btnUprav = new javax.swing.JButton();
        btnVymaz = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbKategoria = new javax.swing.JComboBox();
        cmbPriorita = new javax.swing.JComboBox();
        cmbStav = new javax.swing.JComboBox();
        cmbDenOd = new javax.swing.JComboBox();
        cmbMesOd = new javax.swing.JComboBox();
        cmbRokOd = new javax.swing.JComboBox();
        cmbDenDo = new javax.swing.JComboBox();
        cmbMesDo = new javax.swing.JComboBox();
        cmbRokDo = new javax.swing.JComboBox();
        lblPozadie = new javax.swing.JLabel();

        jButton1.setText("OK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(642, 268));
        getContentPane().setLayout(null);

        lblZnacka.setBackground(new java.awt.Color(204, 153, 255));
        lblZnacka.setFont(new java.awt.Font("Gungsuh", 0, 36)); // NOI18N
        lblZnacka.setText("dori");
        getContentPane().add(lblZnacka);
        lblZnacka.setBounds(350, 190, 85, 42);

        tblUloha.setBackground(new java.awt.Color(204, 204, 204));
        tblUloha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblUloha.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        tblUloha.setModel(ulohaTableModel);
        tblUloha.setGridColor(new java.awt.Color(204, 204, 204));
        tblUloha.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblUloha);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(3, 11, 201, 200);

        lblKategoria.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblKategoria.setText("kategória");
        getContentPane().add(lblKategoria);
        lblKategoria.setBounds(218, 14, 59, 14);

        lblPriorita.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblPriorita.setText("priorita");
        getContentPane().add(lblPriorita);
        lblPriorita.setBounds(228, 45, 49, 14);

        lblStav.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblStav.setText("stav");
        getContentPane().add(lblStav);
        lblStav.setBounds(242, 74, 28, 14);

        lblDatum.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblDatum.setText("dátum od");
        getContentPane().add(lblDatum);
        lblDatum.setBounds(222, 112, 52, 14);

        lblUvod.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblUvod.setText("vlastné filtre");
        getContentPane().add(lblUvod);
        lblUvod.setBounds(455, 11, 169, 14);

        tblFiltre.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        tblFiltre.setModel(filterTableModel);
        tblFiltre.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblFiltre);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 30, 163, 128);

        btnPridaj.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnPridaj.setText("pridaj..");
        btnPridaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPridajActionPerformed(evt);
            }
        });
        getContentPane().add(btnPridaj);
        btnPridaj.setBounds(471, 170, 80, 23);

        btnUprav.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnUprav.setText("uprav..");
        btnUprav.setEnabled(false);
        btnUprav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpravActionPerformed(evt);
            }
        });
        getContentPane().add(btnUprav);
        btnUprav.setBounds(510, 200, 80, 23);

        btnVymaz.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnVymaz.setText("vymaž");
        btnVymaz.setEnabled(false);
        btnVymaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVymazActionPerformed(evt);
            }
        });
        getContentPane().add(btnVymaz);
        btnVymaz.setBounds(560, 170, 67, 23);

        btnOK.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnOK.setText("OK");
        btnOK.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK);
        btnOK.setBounds(222, 173, 62, 17);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 109, 0, 0);

        jLabel5.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        jLabel5.setText("do");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(232, 138, 14, 14);

        cmbKategoria.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbKategoria.setModel(comboBoxModel);
        getContentPane().add(cmbKategoria);
        cmbKategoria.setBounds(287, 11, 100, 20);

        cmbPriorita.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbPriorita.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Nízka", "Stredná", "Vysoká" }));
        getContentPane().add(cmbPriorita);
        cmbPriorita.setBounds(287, 42, 100, 20);

        cmbStav.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbStav.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Nesplnená", "Splnená" }));
        getContentPane().add(cmbStav);
        cmbStav.setBounds(287, 71, 100, 20);

        cmbDenOd.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbDenOd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmbDenOd);
        cmbDenOd.setBounds(287, 110, 50, 20);

        cmbMesOd.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbMesOd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(cmbMesOd);
        cmbMesOd.setBounds(340, 110, 50, 20);

        cmbRokOd.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbRokOd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        cmbRokOd.setLightWeightPopupEnabled(false);
        getContentPane().add(cmbRokOd);
        cmbRokOd.setBounds(390, 110, 60, 20);

        cmbDenDo.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbDenDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cmbDenDo);
        cmbDenDo.setBounds(287, 135, 50, 20);

        cmbMesDo.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbMesDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(cmbMesDo);
        cmbMesDo.setBounds(340, 135, 50, 20);

        cmbRokDo.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        cmbRokDo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        getContentPane().add(cmbRokDo);
        cmbRokDo.setBounds(390, 135, 60, 20);

        lblPozadie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filtrovanieform.png"))); // NOI18N
        getContentPane().add(lblPozadie);
        lblPozadie.setBounds(0, 0, 650, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        List<Uloha> ulohy = ulohaDao.dajVsetky();
        List<Uloha> filtrovaneUlohyKategoriou = new LinkedList<>();
        List<Uloha> filtrovaneUlohyPrioritou = new LinkedList<>();
        List<Uloha> filtrovaneUlohyStavom = new LinkedList<>();
        List<Uloha> filtrovaneUlohyDenOd = new LinkedList<>();
        List<Uloha> filtrovaneUlohyMesiacOd = new LinkedList<>();
        List<Uloha> filtrovaneUlohyRokOd = new LinkedList<>();
        List<Uloha> filtrovaneUlohyDenDo = new LinkedList<>();
        List<Uloha> filtrovaneUlohyMesiacDo = new LinkedList<>();
        List<Uloha> filtrovaneUlohyRokDo = new LinkedList<>();
        if (!cmbKategoria.getSelectedItem().equals(" ")) {
            for (Uloha uloha : ulohy) {
                if (uloha.getKategoria().getNazov().equals(cmbKategoria.getSelectedItem())) {
                    filtrovaneUlohyKategoriou.add(uloha);
                }
            }
        } else {
            filtrovaneUlohyKategoriou = ulohy;
        }
        if (!cmbPriorita.getSelectedItem().equals(" ")) {
            if (filtrovaneUlohyKategoriou != null) {
                for (Uloha uloha : filtrovaneUlohyKategoriou) {
                    if (uloha.getPriorita().equals(cmbPriorita.getSelectedItem())) {
                        filtrovaneUlohyPrioritou.add(uloha);
                    }
                }
            }
        } else {
            filtrovaneUlohyPrioritou = filtrovaneUlohyKategoriou;
        }
        if (!cmbStav.getSelectedItem().equals(" ")) {
            if (filtrovaneUlohyPrioritou != null) {
                for (Uloha uloha : filtrovaneUlohyPrioritou) {
                    Boolean testovanaPodmienka = false;
                    if (cmbStav.getSelectedItem().equals("Splnená")) {
                        testovanaPodmienka = true;
                    }
                    if (uloha.getStav() == testovanaPodmienka) {
                        filtrovaneUlohyStavom.add(uloha);
                    }
                }
            }
        } else {
            filtrovaneUlohyStavom = filtrovaneUlohyPrioritou;
        }
        if (!cmbDenOd.getSelectedItem().equals(" ")) {
            if (filtrovaneUlohyStavom != null) {
                for (Uloha uloha : filtrovaneUlohyStavom) {
                    if (Integer.parseInt(uloha.getDatum().substring(8, 10))
                            >= Integer.parseInt(cmbDenOd.getSelectedItem().toString())) {
                        filtrovaneUlohyDenOd.add(uloha);
                    }
                }
            }
        } else {
            filtrovaneUlohyDenOd = filtrovaneUlohyStavom;
        }
        if (!cmbMesOd.getSelectedItem().equals(" ")) {
            if (filtrovaneUlohyDenOd != null) {
                for (Uloha uloha : filtrovaneUlohyDenOd) {
                    if (Integer.parseInt(uloha.getDatum().substring(5, 7))
                            >= Integer.parseInt(cmbMesOd.getSelectedItem().toString())) {
                        filtrovaneUlohyMesiacOd.add(uloha);
                    }
                }
            }
        } else {
            filtrovaneUlohyMesiacOd = filtrovaneUlohyDenOd;
        }
        if (!cmbRokOd.getSelectedItem().equals(" ")) {
            if (filtrovaneUlohyMesiacOd != null) {
                for (Uloha uloha : filtrovaneUlohyMesiacOd) {
                    if (Integer.parseInt(uloha.getDatum().substring(0, 4))
                            >= Integer.parseInt(cmbRokOd.getSelectedItem().toString())) {
                        filtrovaneUlohyRokOd.add(uloha);
                    }
                }
            }
        } else {
            filtrovaneUlohyRokOd = filtrovaneUlohyMesiacOd;
        }
        if (!cmbDenDo.getSelectedItem().equals(" ")) {
            if (filtrovaneUlohyRokOd != null) {
                for (Uloha uloha : filtrovaneUlohyRokOd) {
                    if (Integer.parseInt(uloha.getDatum().substring(8, 10))
                            <= Integer.parseInt(cmbDenDo.getSelectedItem().toString())) {
                        filtrovaneUlohyDenDo.add(uloha);
                    }
                }
            }
        } else {
            filtrovaneUlohyDenDo = filtrovaneUlohyRokOd;
        }
        if (!cmbMesDo.getSelectedItem().equals(" ")) {
            if (filtrovaneUlohyDenDo != null) {
                for (Uloha uloha : filtrovaneUlohyDenDo) {
                    if (Integer.parseInt(uloha.getDatum().substring(5, 7))
                            <= Integer.parseInt(cmbMesDo.getSelectedItem().toString())) {
                        filtrovaneUlohyMesiacDo.add(uloha);
                    }
                }
            }
        } else {
            filtrovaneUlohyMesiacDo = filtrovaneUlohyDenDo;
        }
        if (!cmbRokDo.getSelectedItem().equals(" ")) {
            if (filtrovaneUlohyMesiacDo != null) {
                for (Uloha uloha : filtrovaneUlohyMesiacDo) {
                    if (Integer.parseInt(uloha.getDatum().substring(0, 4))
                            <= Integer.parseInt(cmbRokDo.getSelectedItem().toString())) {
                        filtrovaneUlohyRokDo.add(uloha);
                    }
                }
            }
        } else {
            filtrovaneUlohyRokDo = filtrovaneUlohyMesiacDo;
        }
        ulohaTableModel.filtruj(filtrovaneUlohyRokDo);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnVymazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVymazActionPerformed
        int vybranyRiadok = tblFiltre.getSelectedRow();
        int vybranyIndexVModeli = tblFiltre.convertRowIndexToModel(vybranyRiadok);
        Filter vybratyFilter = filterTableModel.dajPodlaCislaRiadku(vybranyIndexVModeli);

        if (vybratyFilter == null) {
            return;
        }
        int tlacidlo = JOptionPane.showConfirmDialog(this,
                "Naozaj odstrániť?",
                "Odstránenie úlohy",
                JOptionPane.YES_NO_OPTION
        );
        if (tlacidlo == JOptionPane.YES_OPTION) {
            filterDao.vymazFilter(vybratyFilter);
            aktualizujZoznamFiltrov();
        }
    }//GEN-LAST:event_btnVymazActionPerformed

    private void btnUpravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpravActionPerformed
        int vybranyRiadok = tblFiltre.getSelectedRow();
        int vybranyIndexVModeli
                = tblFiltre.convertRowIndexToModel(vybranyRiadok);
        Filter vybranyFilter
                = filterTableModel.dajPodlaCislaRiadku(vybranyIndexVModeli);
        AddEditFiltreForm upravaFiltrovForm
                = new AddEditFiltreForm(vybranyFilter, (Frame) getOwner());
        upravaFiltrovForm.setVisible(true);
        aktualizujZoznamFiltrov();
    }//GEN-LAST:event_btnUpravActionPerformed

    private void btnPridajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPridajActionPerformed
        AddEditFiltreForm upravaFiltrovForm
                = new AddEditFiltreForm((Frame) getOwner());
        upravaFiltrovForm.setVisible(true);
        aktualizujZoznamFiltrov();
    }//GEN-LAST:event_btnPridajActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FiltrovaniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FiltrovaniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FiltrovaniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FiltrovaniaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FiltrovaniaForm dialog = new FiltrovaniaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPridaj;
    private javax.swing.JButton btnUprav;
    private javax.swing.JButton btnVymaz;
    private javax.swing.JComboBox cmbDenDo;
    private javax.swing.JComboBox cmbDenOd;
    private javax.swing.JComboBox cmbKategoria;
    private javax.swing.JComboBox cmbMesDo;
    private javax.swing.JComboBox cmbMesOd;
    private javax.swing.JComboBox cmbPriorita;
    private javax.swing.JComboBox cmbRokDo;
    private javax.swing.JComboBox cmbRokOd;
    private javax.swing.JComboBox cmbStav;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblKategoria;
    private javax.swing.JLabel lblPozadie;
    private javax.swing.JLabel lblPriorita;
    private javax.swing.JLabel lblStav;
    private javax.swing.JLabel lblUvod;
    private javax.swing.JLabel lblZnacka;
    private javax.swing.JTable tblFiltre;
    private javax.swing.JTable tblUloha;
    // End of variables declaration//GEN-END:variables

    //refresh
    private void aktualizujZoznamFiltrov() {
        filterTableModel.obnov();
    }

    private void aktualizujZoznamUloh() {
        ulohaTableModel.obnov();
    }

}
