/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.ics.upjs.todo.gui;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import sk.ics.upjs.todo.dao.PrihlasovaciARegistrovaciServis;
import sk.ics.upjs.todo.entity.Pouzivatel;
import sk.ics.upjs.todo.exceptions.ZleMenoAleboHesloException;

/**
 *
 * @author kulexpipiens
 */
public class PrihlasovanieForm extends javax.swing.JFrame {

    /**
     * Creates new form PrihasovanieForm
     */
    public PrihlasovanieForm() {
        initComponents();

        setTitle("Prihlásenie");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        txtMeno = new javax.swing.JTextField();
        lblMeno = new javax.swing.JLabel();
        lblHeslo = new javax.swing.JLabel();
        btnRegistracia = new javax.swing.JButton();
        btnPrihlas = new javax.swing.JButton();
        btnZavriet = new javax.swing.JButton();
        txtHeslo = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLogo.setText("Logo");

        txtMeno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMenoKeyPressed(evt);
            }
        });

        lblMeno.setText("Meno:");

        lblHeslo.setText("Heslo");

        btnRegistracia.setText("Registrácia");
        btnRegistracia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistraciaActionPerformed(evt);
            }
        });
        btnRegistracia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegistraciaKeyPressed(evt);
            }
        });

        btnPrihlas.setText("Prihlásiť");
        btnPrihlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrihlasActionPerformed(evt);
            }
        });
        btnPrihlas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnPrihlasKeyPressed(evt);
            }
        });

        btnZavriet.setText("Zavrieť");
        btnZavriet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZavrietActionPerformed(evt);
            }
        });
        btnZavriet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnZavrietKeyPressed(evt);
            }
        });

        txtHeslo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHesloKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMeno)
                        .addGap(18, 18, 18)
                        .addComponent(txtMeno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistracia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btnZavriet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrihlas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeslo)
                        .addGap(18, 18, 18)
                        .addComponent(txtHeslo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeslo)
                    .addComponent(txtHeslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistracia)
                    .addComponent(btnPrihlas)
                    .addComponent(btnZavriet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZavrietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZavrietActionPerformed
        dispose();
    }//GEN-LAST:event_btnZavrietActionPerformed

    private void btnPrihlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrihlasActionPerformed
        String meno = txtMeno.getText();
        String heslo = new String(txtHeslo.getPassword());
        if (meno.equals("") || heslo.equals("")) {
            JOptionPane.showMessageDialog(this,
                    "Zadajte používateľské meno aj heslo!",
                    "Upozornenie", INFORMATION_MESSAGE);
            return;
        }
        try {

            Pouzivatel pouzivatel = new Pouzivatel();
            pouzivatel.setMeno(meno);
            pouzivatel.setHeslo(heslo);

            PrihlasovaciARegistrovaciServis.INSTANCE.prihlas(pouzivatel);

            MainForm.main(null);
            dispose();
        } catch (ZleMenoAleboHesloException e) {
            JOptionPane.showMessageDialog(this, e.getSprava(), "Chyba", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrihlasActionPerformed

    private void btnRegistraciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistraciaActionPerformed
        RegistraciaForm registraciaForm = new RegistraciaForm(this, true);
        registraciaForm.setVisible(true);
    }//GEN-LAST:event_btnRegistraciaActionPerformed

    private void btnPrihlasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnPrihlasKeyPressed
        potvrd(evt);
    }//GEN-LAST:event_btnPrihlasKeyPressed

    private void txtMenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMenoKeyPressed
        potvrd(evt);
    }//GEN-LAST:event_txtMenoKeyPressed

    private void txtHesloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHesloKeyPressed
        potvrd(evt);
    }//GEN-LAST:event_txtHesloKeyPressed

    private void btnZavrietKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnZavrietKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnZavriet.doClick();
        }
    }//GEN-LAST:event_btnZavrietKeyPressed

    private void btnRegistraciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegistraciaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnRegistracia.doClick();
        }
    }//GEN-LAST:event_btnRegistraciaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrihlasovanieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrihlasovanieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrihlasovanieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrihlasovanieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrihlasovanieForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrihlas;
    private javax.swing.JButton btnRegistracia;
    private javax.swing.JButton btnZavriet;
    private javax.swing.JLabel lblHeslo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMeno;
    private javax.swing.JPasswordField txtHeslo;
    private javax.swing.JTextField txtMeno;
    // End of variables declaration//GEN-END:variables

    private void potvrd(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnPrihlas.doClick();
        }
    }
}
