package sk.ics.upjs.todo.gui;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import sk.ics.upjs.todo.dao.PrihlasovaciARegistrovaciServis;
import sk.ics.upjs.todo.entity.Pouzivatel;
import sk.ics.upjs.todo.exceptions.NeplatneRegistracneMenoException;

public class RegistraciaForm extends javax.swing.JDialog {

    private static final VerifikatorVstupov verifikator = GuiFactory.INSTANCE.getVerifikatorVstupov();

    public RegistraciaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        GuiFactory.INSTANCE.centruj(this);
        // v navrharovi nejako nechce ist nastavit farbu, tak to urobime nasilu
        getContentPane().setBackground(GuiFactory.INSTANCE.getFarbaPozadia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        txtMeno = new javax.swing.JTextField();
        lblLogo = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtHeslo = new javax.swing.JPasswordField();
        lblMeno = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblHeslo = new javax.swing.JLabel();
        btnRegistruj = new javax.swing.JButton();
        btnZavri = new javax.swing.JButton();
        chkChceNotifikacie = new javax.swing.JCheckBox();
        txtDobaNotifikacie = new javax.swing.JTextField();
        lblCasNotifikacie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtMeno, org.jdesktop.beansbinding.ELProperty.create("Meno"), txtMeno, org.jdesktop.beansbinding.BeanProperty.create("name"));
        bindingGroup.addBinding(binding);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); // NOI18N
        lblLogo.setMinimumSize(new java.awt.Dimension(315, 161));
        lblLogo.setPreferredSize(new java.awt.Dimension(315, 161));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtMail, org.jdesktop.beansbinding.ELProperty.create("E-mail"), txtMail, org.jdesktop.beansbinding.BeanProperty.create("name"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtHeslo, org.jdesktop.beansbinding.ELProperty.create("Heslo"), txtHeslo, org.jdesktop.beansbinding.BeanProperty.create("name"));
        bindingGroup.addBinding(binding);

        lblMeno.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblMeno.setText("Meno:");

        lblMail.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblMail.setText("E-mail:");

        lblHeslo.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblHeslo.setText("Heslo:");

        btnRegistruj.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnRegistruj.setText("Registrovať");
        btnRegistruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrujActionPerformed(evt);
            }
        });

        btnZavri.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        btnZavri.setText("Zavrieť");
        btnZavri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZavriActionPerformed(evt);
            }
        });

        chkChceNotifikacie.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        chkChceNotifikacie.setText("Chcem dostávať na mail notifikácie o úlohách");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtDobaNotifikacie, org.jdesktop.beansbinding.ELProperty.create("čas do splnenia úlohy"), txtDobaNotifikacie, org.jdesktop.beansbinding.BeanProperty.create("name"));
        bindingGroup.addBinding(binding);

        lblCasNotifikacie.setFont(new java.awt.Font("Gungsuh", 0, 11)); // NOI18N
        lblCasNotifikacie.setText("hod. pred časom splnenia úlohy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMeno)
                            .addComponent(lblMail)
                            .addComponent(lblHeslo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMeno, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(txtMail)
                            .addComponent(txtHeslo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnZavri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistruj))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkChceNotifikacie)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDobaNotifikacie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCasNotifikacie)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMeno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeslo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkChceNotifikacie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDobaNotifikacie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCasNotifikacie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistruj)
                    .addComponent(btnZavri))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnZavriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZavriActionPerformed
        dispose();
    }//GEN-LAST:event_btnZavriActionPerformed

    private void btnRegistrujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrujActionPerformed
        try {
            Pouzivatel pouzivatel = new Pouzivatel();

            String meno = txtMeno.getText();
            String heslo = new String(txtHeslo.getPassword());
            if (meno.isEmpty() || heslo.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Zadajte používateľské meno aj heslo!",
                        verifikator.getNadpis(), ERROR_MESSAGE);
                return;
            }
            pouzivatel.setMeno(meno);
            pouzivatel.setHeslo(heslo);

            if (!verifikator.jeEmail(txtMail)) {
                JOptionPane.showMessageDialog(this, "Zadajte email v správnom formáte!",
                        verifikator.getNadpis(), ERROR_MESSAGE);
                return;
            }
            pouzivatel.setMail(txtMail.getText());

            pouzivatel.setChceNotifikacie(chkChceNotifikacie.isSelected());

            String dobaNotifikacie = txtDobaNotifikacie.getText();
            // overenie pre pripad, ze uzivatel nezadal do doby notifikacie nic
            if (dobaNotifikacie.isEmpty()) {
                pouzivatel.setDobaNotifikacie(null);
            } // ak zadal cislo v zlom formate
            else if (!verifikator.jeCeleCislo(txtDobaNotifikacie)) {
                JOptionPane.showMessageDialog(this, "Zadajte dobu notifikácie v správnom formáte!",
                        verifikator.getNadpis(), ERROR_MESSAGE);
                return;
            } else {
                pouzivatel.setDobaNotifikacie(Integer.valueOf(dobaNotifikacie));
            }

            PrihlasovaciARegistrovaciServis.INSTANCE.zaregistruj(pouzivatel);

            JOptionPane.showMessageDialog(this, "Registrácia prebehla úspešne, môžete sa prihlásiť!",
                    "Informácia", INFORMATION_MESSAGE);
            dispose();
        } catch (NeplatneRegistracneMenoException e) {
            JOptionPane.showMessageDialog(this, e.getSprava(), "Chyba", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistraciaForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistraciaForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistraciaForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistraciaForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistraciaForm dialog = new RegistraciaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistruj;
    private javax.swing.JButton btnZavri;
    private javax.swing.JCheckBox chkChceNotifikacie;
    private javax.swing.JLabel lblCasNotifikacie;
    private javax.swing.JLabel lblHeslo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMeno;
    private javax.swing.JTextField txtDobaNotifikacie;
    private javax.swing.JPasswordField txtHeslo;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMeno;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
